from numpy import NaN
import os
import pandas as pd
import pytest
from etls.instructions import instructions

DATA_DIRECTORY = os.path.join(os.path.dirname("__file__"), "data")

pat_pop_delta_counts = {
    "OCT_DATE": 6,
    "Sub-RPE 5mm OD": 1079,
    "dist_fovea_OD": 1,
    "cst_OD": 2,
    "Sub-RPE 5mm OS": 448,
    "questionable_OS": 2,
}

opthafterdxdate_delta_counts = {
    "BUN result 30 days after Contact_DATE": 2,
    "LDL result 30 days after Contact_DATE": 7,
    "Glucose result 30 days after Contact_DATE": 2,
    "Serum Creatinine date 30 days after Contact_DATE": 4,
    "cst_OS": 1,
    "dist_fovea OS": 1,
    "Sub-RPE 5mm OS": 121,
    "dist_fovea OD": 3,
    "Sub-RPE 5mm OD": 116,
    "VA_Left_Pressure": 133,
    "VA_Left_Distance_CC": 5147, 
    "VA_Right_Pressure": 133,
    "VA_Right_Distance_SC": 2541,
    "VA_Left_Distance_SC":2782,
    "VA_Right_Distance_CC": 4871
}

@pytest.fixture(scope="session", autouse=True)
def mock_VA_sheet():
    return pd.read_excel(os.path.join(DATA_DIRECTORY, "raw", "ccf_apellis_data_cleaning_summary_20231120.xlsx"), sheet_name="ophth after DXDate_11")

@pytest.fixture(scope="session", autouse=True)
def mock_pat_pop():
    try:
        return pd.read_csv(os.path.join(DATA_DIRECTORY, "interim", "pat_pop.csv"))
    except:
        return None


@pytest.fixture(scope="session", autouse=True)
def mock_dxafterdxdate():
    try:
        return pd.read_csv(os.path.join(DATA_DIRECTORY, "interim", "dxafterdxdate.csv"))
    except:
        return None

@pytest.fixture(scope="session", autouse=True)
def mock_ophthafterdxdate():
    try:
        return pd.read_csv(os.path.join(DATA_DIRECTORY, "interim", "ophthafterdxdate.csv"))
    except:
        return None


@pytest.fixture(scope="session", autouse=True)
def mock_pat_pop_instructions():
    return instructions["pat_pop"]


mock_oct_date_notes = [
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    "NO ATROPHY",
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    "NO ATROPHY",
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    "OD CONVERTS TO WET",
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
]

mock_sub_rpe_od_notes = [
    NaN,
    NaN,
    "ONLY ONE IMAGE",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "NO ATROPHY",
    NaN,
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    NaN,
    "PDR",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "WET AMD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "WET AMD",
    "WET AMD",
    NaN,
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "TOGA STUDY",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    NaN,
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "NO ATROPHY AT BASELINE BUT DEVELOPS DURING FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "ONLY ONE IMAGE",
    NaN,
    NaN,
    "ONLY ONE IMAGE",
    "NO ATROPHY",
    NaN,
    NaN,
    NaN,
    "INT AMD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "ONLY ONE IMAGE",
    "LESS THAN ONE YEAR FOLLOW UP",
    "WET AMD",
    NaN,
    NaN,
    NaN,
    "LAMELLAR HOLE",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW UP",
    "ONLY ONE IMAGE",
    "IMAGES NOT APPEARING IN ZEISS",
    "NO ATROPHY AT BASELINE BUT DEVELOPS DURING FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    NaN,
    "NO AMD",
    NaN,
    "EXUDATIVE AMD",
    "IMAGES NOT APPEARING NEAR FIRST DIAGNOSIS DATE",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "NO ATROPHY",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "VITELLIFORM DYSTROPHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "WET AMD",
    "NO ATROPHY",
    NaN,
    NaN,
    NaN,
    "SEVERE NPDR",
    NaN,
    "WET AMD",
    "HX OF ANTI-VEGF",
    "NO ATROPHY",
    "WET AMD",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "INT AMD",
    "ONLY ONE IMAGE",
    NaN,
    "WET AMD",
    NaN,
    NaN,
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW UP",
    "WET AMD",
    NaN,
    "NO ATROPHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    "WET AMD",
    "ONLY ONE IMAGE",
    "LESS THAN ONE YEAR FOLLOW UP",
    "ONLY ONE IMAGE",
    "ONLY ONE IMAGE",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "ONLY ONE IMAGE",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "CRVO",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "NO ATROPHY",
    NaN,
    "NO ATROPHY AT BASELINE BUT DEVELOPS DURING FOLLOW-UP",
    "NO ATROPHY",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "WET OD",
    "WET AMD",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    NaN,
    "PATTERN DYSTROPHY VS VITELLIFORM",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    NaN,
    "NO AMD OD",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "IMAGES NOT APPEARING IN ZEISS",
    "IMAGES NOT APPEARING IN ZEISS",
    "NO GA OD",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    "Exudative age-related macular degeneration OD",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "WET OD",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "IMAGES NOT APPEARING IN ZEISS",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW UP",
    "RVO",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "IMAGES NOT APPEARING IN ZEISS",
    "WET AMD",
    NaN,
    "WET OU",
    "Exudative age-related macular degeneration OD",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    "CRVO OD",
    "NO ATROPHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "WET OD",
    "LESS THAN ONE YEAR FOLLOW UP",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "WET OD",
    "WET OD",
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    "NO ATROPHY",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "DIABETIC RETINOPATHY OU",
    "Exudative age-related macular degeneration OD & OS",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "DIABETIC RETINOPATHY",
    "Exudative age-related macular degeneration OD & OS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    "Exudative age-related macular degeneration OD & OS",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "CONVERTS TO WET OU WITHIN 1 YEAR",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "NO DX OF AMD",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Exudative age-related macular degeneration OD",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "DIABETIC RETINOPATHY",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "DIABETIC RETINOPATHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "Exudative age-related macular degeneration OD",
    "NO ATROPHY",
    "Exudative age-related macular degeneration OD",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Exudative age-related macular degeneration OD & OS",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "DIABETIC RETINOPATHY",
    "BRVO OD",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    NaN,
    NaN,
    "Exudative age-related macular degeneration OD",
    "Exudative age-related macular degeneration OD",
    NaN,
    "Exudative age-related macular degeneration OD",
    "Exudative OU?",
    NaN,
    "Exudative age-related macular degeneration OD & OS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "Exudative?",
    "Exudative age-related macular degeneration OD & OS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Exudative age-related macular degeneration OU",
    "Exudative age-related macular degeneration OD & OS",
    NaN,
    "Exudative age-related macular degeneration OD & OS",
    "Exudative age-related macular degeneration OD",
    "Exudative age-related macular degeneration OD",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "Exudative age-related macular degeneration OD & OS",
    "NO ATROPHY",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "NO ATROPHY",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "WET AMD",
    "Exudative age-related macular degeneration OD",
    NaN,
    "VITELLIFORM/PATTERN",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "Exudative age-related macular degeneration OD",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    NaN,
    "NO ATROPHY",
    "Exudative age-related macular degeneration OD & OS",
    NaN,
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Exudative age-related macular degeneration OD",
    "NO DX OF AMD",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "NO ATROPHY",
    NaN,
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "Exudative age-related macular degeneration OD",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    NaN,
    "NO AMD",
    NaN,
    NaN,
    "Exudative age-related macular degeneration OD",
    NaN,
    "WET AMD",
    NaN,
    NaN,
    NaN,
    NaN,
    NaN,
    "CATALINA STUDY PARTICIPANT",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "NO ATROPHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "Exudative age-related macular degeneration OD & OS",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "DIABETIC RETINOPATHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "IMAGES NOT APPEARING IN ZEISS",
    "IMAGING QUALITY POOR",
    "LESS THAN ONE YEAR FOLLOW UP",
    "DIABETIC MACULAR EDEMA OD & OS",
    NaN,
    NaN,
    NaN,
    "HEREDITARY MACULAR DYSTROPHY",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "IMAGES NOT APPEARING IN ZEISS",
    "MAC HOLE ",
    "IMAGES NOT APPEARING IN ZEISS",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "Exudative age-related macular degeneration OD & OS",
    "Exudative age-related macular degeneration OD",
    NaN,
    "UVEITIS OD",
    NaN,
    "NO ATROPHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "Exudative age-related macular degeneration OD",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Exudative age-related macular degeneration OD",
    "POSSIBLE MYOPIC DEGEN",
    "IMAGES NOT APPEARING IN ZEISS",
    "WET AMD",
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "IMAGES NOT APPEARING IN ZEISS",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    NaN,
    "NPDR BILAT",
    "PATTERN DYSTROPHY",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    NaN,
    "LAMELLAR HOLE",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Exudative age-related macular degeneration OD",
    "IMAGES NOT APPEARING IN ZEISS",
    "RETINAL DETACHMENT",
    "IMAGES NOT APPEARING IN ZEISS",
    "PATTERN INCONSISTENT WITH AMD",
    "LESS THAN ONE YEAR FOLLOW UP",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "NO ATROPHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "Exudative age-related macular degeneration OD & OS",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "NO ATROPHY",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    NaN,
    "Exudative age-related macular degeneration OD",
    NaN,
    "Exudative age-related macular degeneration OD & OS",
    NaN,
    NaN,
    "NO AMD",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "NO ATROPHY",
    "IMAGES NOT APPEARING IN ZEISS",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    "PEHCR OD",
    "NO BASELINE ATROPHY",
    NaN,
    "LAMPA STUDY",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "TOGA STUDY",
    "Exudative age-related macular degeneration OD",
    NaN,
    NaN,
    "MACULAR HOLE OD",
    NaN,
    "Exudative age-related macular degeneration OD",
    "IMAGES NOT APPEARING IN ZEISS",
    "Degenerative Myopia OU",
    "CME OU",
    "LIKELY PATTERN DYSTROPHY",
    NaN,
    NaN,
    "Exudative age-related macular degeneration OD",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET OD",
    NaN,
    "NO IMAGES AVAILABLE FOR THE DXDATE, FOLLOW-UPS ARE",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "Hx ANTI-VEGF OU",
    "NO IMAGES AVAILABLE FOR THE DXDATE, FOLLOW-UPS ARE",
    "NO GA",
    NaN,
    "NO IMAGES AVAILABLE FOR THE DXDATE, FOLLOW-UPS ARE",
    NaN,
    "NO GA OU",
    "WET OD",
    "NO AMD / GA (incorrect coding)",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO GA OD",
    NaN,
    "WET OD",
    "NO GA OU",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "NO GA",
    "NO IMAGES AVAILABLE FOR THE DXDATE, FOLLOW-UPS ARE",
    NaN,
    "NO GA OD",
    "GA vs STARGARDT'S DISEASE OU- DIAGNOSIS NOT CERTAIN YET",
    "WET OU",
    "WET OD",
    "LESS THAN 1 YEAR NONEXUDATIVE",
    "WET OD",
    "NO IMAGES AVAILABLE FOR THE DXDATE, FOLLOW-UPS ARE",
    "NO IMAGES AVAILABLE FOR THE DXDATE, FOLLOW-UPS ARE",
    "NO GA BY IMAGING",
    "WET OD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO GA BY IMAGING",
    "NO GA OU",
    "NO GA BY IMAGING",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "WET OD",
    "WET AMD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO GA OD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET OD",
    "WET OD",
    "WET OD",
    "NO GA OU",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET OD",
    NaN,
    "WET OD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO GA OD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET OD",
    "Diabetic retinopathy OU",
    "NO IMAGES AVAILABLE FOR THE DXDATE, FOLLOW-UPS ARE",
    "NO GA BY IMAGING",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO GA OU",
    "INCORRECT CODING AND NO VISIT ON DATE",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "WET OD, Diabetic retinopathy OU",
    "RVO w/Macular Edema OD",
    "IMAGES NOT APPEARING IN ZEISS",
    "IMAGES NOT APPEARING IN ZEISS",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    NaN,
    "WET OD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET OD",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    "WET AMD",
    NaN,
    NaN,
    "NO GA OD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "PRESENCE OF OTHER MACULOPATHY",
    NaN,
    NaN,
    NaN,
    NaN,
    "PATTERN DYSTROPHY",
    NaN,
    "NO GA BY IMAGING",
    "SUSPECTED COMORBID DR OD",
    "NO GA",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET OD",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "HX ANTI-VEGF INJECTIONS OD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT APPEARING IN ZEISS",
    "PDR OU",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    NaN,
    "WET OD",
    NaN,
    "NO ATROPHY",
    NaN,
    "WET OU",
    "INT AMD",
    "WET OD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    'ZEISS ERROR: "PATIENT NOT UNIQUE"',
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    "Macular hole OD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO ATROPHY",
    NaN,
    "NO ATROPHY",
    NaN,
    "NPDR OU",
    NaN,
    "NO GA OU",
    "NO GA OU",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "DR OU",
    "Myopic degeneration OU",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "Intermideate AMD",
    NaN,
    "WET OU",
    NaN,
    "NO GA OU",
    NaN,
    "LESS THAN 1 YEAR FOLLOW-UP",
    NaN,
    NaN,
    "NO GA OU",
    NaN,
    "LESS THAN 1 YEAR FOLLOW-UP",
    "NO GA OU",
    NaN,
    "LESS THAN 1 YEAR FOLLOW-UP",
    "NO GA OU",
    "OTHER MACULOPATHY OU",
    NaN,
    NaN,
    NaN,
    "CRVO w/macular edema OD",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    "DR OU",
    NaN,
    "Images not avaliable in Zeiss",
    "LESS THAN 1 YEAR FOLLOW-UP",
    "WET OD",
    "WET OD",
    "LESS THAN 1 YEAR FOLLOW-UP",
    "WET OU",
    "Images not avaliable in Zeiss",
    "NO GA OU",
    "NO GA OD until 6/23/2021",
    "WET OU",
    "WET OU",
    "BRVO OD",
    NaN,
    "NO GA OD",
    NaN,
    NaN,
    "ANTI-VEGF OD",
    "CONVERTS TO WET OU WITHIN 1 YEAR",
    "NO GA OU",
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    "LESS THAN 1 YEAR FOLLOW-UP",
    NaN,
    NaN,
    "WET OD",
    "Hx LAMPA TRIAL ",
    "LESS THAN 1 YEAR FOLLOW-UP",
    "LESS THAN 1 YEAR FOLLOW-UP",
    NaN,
    "LESS THAN 1 YEAR FOLLOW-UP",
    NaN,
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    "LESS THAN 1 YEAR FOLLOW-UP",
    "NO GA OD",
    NaN,
    "WET OU",
    NaN,
    "WET OD",
    "NO GA",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    NaN,
    "LESS THAN 1 YEAR FOLLOW-UP",
    "MACULAR EDEMA OD",
    "MACULAR EDEMA OU, SOURCE UNSPECIFIED IN NOTE",
    "LESS THAN 1 YEAR FOLLOW-UP",
    NaN,
    "APL-2 DRY AMD STUDY",
    NaN,
    NaN,
    NaN,
    "WET OD",
    "LESS THAN 1 YEAR FOLLOW-UP",
    "NO GA OD",
    "LESS THAN 1 YEAR FOLLOW-UP",
    NaN,
    "LESS THAN 1 YEAR FOLLOW-UP",
    "LESS THAN 1 YEAR FOLLOW-UP",
    "LESS THAN 1 YEAR FOLLOW-UP",
    "Hx ANTI-VEGF OU",
    "T2DR OU",
    "LESS THAN 1 YEAR FOLLOW-UP",
    NaN,
    "IMAGES NOT APPEARING IN ZEISS",
    NaN,
    NaN,
    "INT OD",
    NaN,
    "<1 year follow-up",
    NaN,
    "<1 year follow-up",
    "No Images on Zeiss",
    "INT AMD",
    NaN,
    "<1 year follow-up",
    "<1 year follow-up with images",
    "Excluded for presence of Lacquer cracks OU",
    "INT AMD",
    NaN,
    "<1 year follow-up",
    NaN,
    "INT AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "No Images on Zeiss",
    "NO ATROPHY",
    NaN,
    "exudative AMD",
    "<1 year follow-up",
    NaN,
    "INT AMD",
    "<1 year follow-up",
    "No Images on Zeiss",
    "<1 year follow-up",
    "<1 year follow-up",
    NaN,
    "No Images on Zeiss",
    "<1 year follow-up",
    "<1 year follow-up",
    NaN,
    NaN,
    "<1 year follow-up",
    "<1 year follow-up",
    NaN,
    "exudative AMD",
    "INT AMD",
    "<1 year follow-up",
    NaN,
    "INT AMD",
    NaN,
    "exudative AMD",
    NaN,
    NaN,
    "<1 year follow-up with imaging",
    "HRVO and exudative AMD",
    NaN,
    "<1 year follow-up",
    NaN,
    "No Images on Zeiss when dry AMD",
    NaN,
    "No Images on Zeiss",
    "<1 year follow-up",
    "exudative AMD",
    "No Images on Zeiss",
    "<1 year follow-up",
    "<1 year follow-up",
    "exudative AMD",
    "INT AMD",
    "Retinal dystrophy",
    NaN,
    "Moderate NPDR bilaterally",
    "NO IMAGES AVAILABLE",
    NaN,
    "INT AMD",
    "INT AMD",
    "<1 year follow-up",
    NaN,
    "Exudative AMD ",
    "<1 year follow-up",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    NaN,
    "UVEITIS",
    NaN,
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "exudative AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    NaN,
    " Maculopothy (Vitelliform) ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    NaN,
    "exudative AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "PDR OU",
    "exudative AMD",
    "<1 year follow-up",
    "<1 year follow-up",
    "INT AMD",
    "<1 year follow-up",
    NaN,
    "exudative AMD",
    "<1 year follow-up",
    NaN,
    "exudative AMD",
    "<1 year follow-up",
    "INT AMD & Vitelliform",
    "Exudative AMD",
    "<1 year follow-up",
    "INT AMD",
    "<1 year follow-up",
    " Mild Nonproliferative Retinopathy ",
    "Unspecified Schesis & Conversion to Exudative AMD ",
    "exudative AMD",
    "INT AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up",
    "<1 year follow-up",
    "<1 year follow-up",
    "<1 year follow-up",
    "INT AMD",
    "GA APPEARS 1/9/2019",
    "<1 year follow-up",
    "<1 year follow-up",
    "<1 year follow-up",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up",
    "Maculopothy (Pattern Dystrophy) ",
    NaN,
    "<1 year follow-up",
    "<1 year follow-up",
    "<1 year follow-up",
    "NO GA",
    "<1 year follow-up",
    "<1 year follow-up",
    "INT AMD",
    NaN,
    "<1 year follow-up",
    "INT AMD",
    "exudative AMD",
    "<1 year follow-up",
    "exudative AMD",
    "exudative AMD",
    NaN,
    NaN,
    "<1 year follow-up",
    "INT AMD",
    "<1 year follow-up",
    "<1 year follow-up",
    "BRVO",
    NaN,
    "Chroioretinopathy & Injections ",
    "No AMD",
    NaN,
    "<1 year follow-up with non-exudative AMD",
    "<1 year follow-up ",
    "<1 year follow-up ",
    NaN,
    "WET AMD",
    "<1 year follow-up with non-exudative AMD",
    "WET AMD",
    "INT AMD",
    "Hx ANTI-VEGF OU",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "INT AMD",
    "WET AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    NaN,
    NaN,
    "<1 year follow-up ",
    NaN,
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    "<1 year follow-up ",
    NaN,
    "WET AMD",
    "<1 year follow-up with non-exudative AMD",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "WET/EDEMA OD",
    "<1 year follow-up with non-exudative AMD",
    "INT AMD",
    "DR",
    "WET AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    NaN,
    "<1 year follow-up ",
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "INT AMD",
    "WET AMD",
    "<1 year follow-up with imaging ",
    "<1 year follow-up ",
    NaN,
    "<1 year follow-up ",
    "INT AMD",
    NaN,
    "No GA",
    NaN,
    "<1 year follow-up ",
    NaN,
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "exudative AMD",
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    "<1 year follow-up ",
    "WET AMD",
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    NaN,
    NaN,
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    NaN,
    "INT AMD",
    NaN,
    "NO GA ON IMAGING",
    "FOLLOW-UP VISITS NOT IMPORTED INTO SPREADSHEET",
    "<1 year follow-up ",
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    "INT AMD",
    "WET AMD",
    "<1 year follow-up with imaging",
    "<1 year follow-up ",
    "INT AMD",
    "<1 year follow-up ",
    "<1 year follow-up ",
    "<1 year follow-up ",
    NaN,
    "Macular hole OD",
    NaN,
    "WET AMD",
    NaN,
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    NaN,
    "Pattern Dystrophy",
    "<1 year follow-up ",
    "INT AMD",
    "INT AMD",
    "WET AMD",
    "INT AMD/NO GA",
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    "WET OD WITHIN 1 YR",
    "<1 year follow-up ",
    "CONVERTS TO WET OU WITHIN 1 YEAR",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    "T2 DR OU",
    "<1 year follow-up ",
    "WET AMD",
    NaN,
    "INT AMD",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "<1 year follow-up ",
    "<1 year follow-up ",
    NaN,
    "<1 year follow-up ",
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    "WET AMD",
    "WET AMD",
    "<1 year follow-up ",
    "WET AMD",
    "<1 year follow-up ",
    "WET AMD",
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    "CONVERTS TO WET WITHIN 1 YR",
    NaN,
    NaN,
    'ZEISS ERROR: "PATIENT NOT FOUND"',
    NaN,
    NaN,
    NaN,
    "WET AMD",
    NaN,
    "WET AMD",
    NaN,
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    "WET AMD",
    NaN,
    NaN,
    NaN,
    "HX PHOTODYNAMIC THERAPY",
    "WET AMD",
    "LAMELLAR HOLE",
    "WET AMD",
    "<1 year follow-up ",
    "WET AMD",
    "<1 year follow-up ",
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "WET AMD",
    "<1 year follow-up ",
    NaN,
    "<1 year advanced RPE data",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    NaN,
    "PATIENT NOT AVAILABLE IN ZEISS",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "DME bilaterally ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "Adult Vitelliform Dystrophy ",
    "Early AMD",
    NaN,
    NaN,
    "Adult Vitelliform Dystrophy and < 1yr follow-up",
    "NO GA ON IMAGING",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    "Unclear AMD vs Vitelliform Dystrophy",
    NaN,
    NaN,
    "<1 year follow-up ",
    "WET AMD",
    NaN,
    NaN,
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "<1 year follow-up ",
    "Intermediate at baseline but develops atrophy",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    "<1 year follow-up ",
    "WET AMD",
    "<1 year follow-up ",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO GA ON IMAGING",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "Uveitis",
    "<1 year follow-up ",
    "<1 year follow-up ",
    "<1 year follow-up ",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up ",
    "WET AMD",
    NaN,
    "ANTI-VEGF OD",
    "<1 year follow-up non-exudative",
    NaN,
    "GAllegOLe STUDY",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up non-exudative",
    "<1 year follow-up non-exudative",
    "<1 year follow-up ",
    "<1 year follow-up ",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    NaN,
    "INT AMD",
    "WET AMD",
    "INT AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "<1 year follow-up non-exudative",
    "WET AMD",
    NaN,
    NaN,
    NaN,
    "<1 year follow-up ",
    "<1 year follow-up ",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "MILD NPDR",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "WET AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    NaN,
    NaN,
    "WET AMD - RECEIVED ONE INJECTION SEVERAL YEARS PRIOR",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR IMAGING DATA",
    "FORMERLY PART OF AART STUDY",
    NaN,
    NaN,
    "WET AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "MODERATE NPDR",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "CNVM",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "MORE LIKELY PATTERN DYSTROPHY OR INACTIVE CSR",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR IMAGING DATA; ADDITIONALLY PATIENT WITH EXTENSIVE SURGIES DURING FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "LESS THAN ONE YEAR IMAGING",
    "LESS THAN ONE YEAR NONEXUDATIVE",
    "NO ADVANCED RPE AT BASELINE BUT AVAILABLE THROUGHOUT FOLLOW-UP",
    "WET AMD",
    "INTERMEDIATE AMD UNTIL 8/24/20",
    "WET AMD",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    NaN,
    NaN,
    "NO ATROPHY - i-ORA at worst",
    "LESS THAN ONE YEAR IMAGING",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR IMAGING",
    "WET AMD",
    "WET AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "MYOPIC DEGENERATION ",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "MYOPIC DEGEN VS OCULAR HISTOPLASMOSIS ",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    NaN,
    "VITELLIFORM LESION/DRUSEN BUT NO ATROPHY ",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "CRVO",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR NONEXUDATIVE",
    "ADVANCED RPE ANALYSIS AVAILABLE LESS THAN ONE YEAR",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO ADVANCED RPE AT BASELINE BUT AVAILABLE THROUGHOUT FOLLOW-UP",
    NaN,
    "WET AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR NONEXUDATIVE",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR NONEXUDATIVE",
    "LESS THAN ONE YEAR NONEXUDATIVE",
    NaN,
    "ONLY ONE SET OF MEASUREMENTS",
    "HEREDITARY MACULAR DYSTROPHY",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO ATROPHY",
    "NO IMAGES AVAILABLE FOR DXDATE, FOLLOW-UPS ARE",
    "WET AMD",
    "LESS THAN ONE YEAR NONEXUDATIVE",
    NaN,
    "WET AMD",
    NaN,
    "TOGA STUDY",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO ATROPHY",
    "NO ATROPHY",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "MAC HOLE",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO ATROPHY",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "ONLY ONE SET OF MEASUREMENTS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO ATROPHY",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    NaN,
    "ONLY ONE SET OF MEASUREMENTS",
    "NO ATROPHY",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    NaN,
    NaN,
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    NaN,
    "WET AMD",
    NaN,
    NaN,
    NaN,
    "NO ATROPHY",
    "WET AMD",
    NaN,
    "Laser Tx OU and Novak Inj",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "WET AMD",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "ONLY ONE IMAGE",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "CLINICAL TRIAL PARTICIPANT (APELLIS TRIAL)",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO ATROPHY",
    "ADVANCED RPE ANALYSIS AVAILABLE <1 YEAR",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "NO ATROPHY",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    NaN,
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "WET AMD",
    "Int OD",
    "WET AMD",
    "WET AMD",
    "NO ATROPHY",
    "WET AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "ONLY ONE IMAGE",
    "MILD NPDR",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "NO ATROPHY",
    "NECROTIZING SCLERITIS",
    "WET AMD",
    "WET AMD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "MAC HOLE ",
    "WET AMD",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "Advanced RPE Analysis unavailable at baseline but available during follow-up",
    "NO ATROPHY",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    "LESS THAN ONE YEAR BEFORE CONVERSION TO WET",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    "INT AMD",
    NaN,
    NaN,
    "IMAGES NOT AVAILABLE IN ZEISS",
    "WET AMD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "NO ATROPHY",
    NaN,
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    "WET AMD",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "INT AMD",
    NaN,
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    "NO GA",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    "WET AMD",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "BRVO",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "CRVO",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    "WET AMD",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "ONLY ONE IMAGE",
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LAMELLAR MACULAR HOLE",
    "WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "INT AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "INACTIVE WET AMD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "MACULAR HOLE OD",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "WET AMD",
    NaN,
    NaN,
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "CRVO",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "INT AMD",
    "WET AMD",
    "HX INJECTIONS",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR FOLLOW-UP",
    "LESS THAN ONE YEAR IMAGING DATA",
    "LESS THAN ONE YEAR FOLLOW UP",
    "IMAGES NOT AVAILABLE IN ZEISS",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "ONLY ONE SET OF MEASUREMENTS",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    NaN,
    "LESS THAN ONE YEAR FOLLOW UP",
    "BRVO",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
    "LESS THAN ONE YEAR FOLLOW UP",
]
