instructions = {
    "pat_pop": {
        "OCT_DATE": {
            "format": "date",
            "string_intention": "mixed",
            "vals_to_notes": ["NO ATROPHY", "OD CONVERTS TO WET"],
        },
        "Sub-RPE 5mm OD": {"format": "numeric", "string_intention": "notes"},
        "dist_fovea_OD": {"format": "numeric", "string_intention": "blank"},
        "cst_OD": {"format": "numeric", "string_intention": "notes"},
        "Sub-RPE 5mm OS": {"format": "numeric", "string_intention": "notes"},
        "questionable_OS": {"format": "numeric", "string_intention": "blank"},
    },
    "dxafterdxdate": {
        "CURRENT_ICD9_LIST": {"format": "string", "string_intention": "split"}
    },
    "ophthafterdxdate": {
        "BUN result 30 days after Contact_DATE": {
            "format": "numeric",
            "string_intention": "blank",
        },
        "LDL result 30 days after Contact_DATE": {
            "format": "numeric",
            "string_intention": "blank",
        },
        "Glucose result 30 days after Contact_DATE": {
            "format": "numeric",
            "string_intention": "blank",
        },
        "cst_OS": {"format": "numeric", "string_intention": "blank"},
        "dist_fovea OS": {"format": "numeric", "string_intention": "blank"},
        "Sub-RPE 5mm OS": {"format": "numeric", "string_intention": "notes"},
        "dist_fovea OD": {"format": "numeric", "string_intention": "blank"},
        "Sub-RPE 5mm OD": {"format": "numeric", "string_intention": "notes"},
        "VA_Left_Distance_CC": {
            "format": "string",
            "string_intention": "map",
            "args": {
                "sheet_name": "ophth after DXDate_14",
                "num_head": 15,
                "num_tail": 16,
                "num_cols": "A:C",
                "str_head": 39,
                "str_tail": 1045,
                "str_cols": "A:C",
            },
        },
        "VA_Right_Distance_SC": {"format": "string", 
                                 "string_intention":"map", 
                                 "args": {"sheet_name":"ophth after DXDate_11",
                                          "num_head":15,
                                          "num_tail": 4,
                                          "num_cols":"A:C",
                                          "str_head": 30,
                                          "str_tail":566,
                                          "str_cols": "A:C"}},
        "VA_Left_Distance_SC": {"format": "string",
                                "string_intention": "map",
                                "args": {"sheet_name":"ophth after DXDate_12",
                                         "num_head": 15,
                                         "num_tail": 3,
                                         "num_cols": "A:C",
                                         "str_head": 31,
                                         "str_tail": 659,
                                         "str_cols":"A:C"}},
        "VA_Right_Distance_CC": {"format":"string",
                                 "string_intention": "map",
                                 "args":{"sheet_name": "ophth after DXDate_13",
                                         "num_head": 15,
                                         "num_tail": 18,
                                         "num_cols": "A:C",
                                         "str_head": 41,
                                         "str_tail": 891,
                                         "str_cols": "A:C"}},
        "VA_Right_Pressure": {"format":"string",
                              "string_intention": "map",
                              "args": {"sheet_name": "ophth after DXDate_15",
                                       "str_head": 31,
                                       "str_tail": 37,
                                       "str_cols":"A:C"}},
        "VA_Left_Pressure": {"format":"string",
                             "string_intention": "map",
                             "args": {"sheet_name":"ophth after DXDate_16",
                                      "str_head": 31,
                                      "str_tail":40,
                                      "str_cols":"A:C"}}

    },
}
