name: Unit Tests
on:
  push:
    branches: [ main, develop, feature*]
  pull_request:
    branches: [main, develop ]
jobs: 
  self-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Run locla action
    - name: Test action-setup-venv
      id: venv
      with:
        python-version: 3.11
        install-cmd: pip install -r requirements.txt

    # Print debug vars
    - name: Print variables for debugging
      run: |
        echo "VIRTUAL_ENV: ${VIRTUAL_ENV}"
        echo "PATH: ${PATH}"
    
    - name: Test with pytest
      run: |
        pytest tests
